#!/bin/bash

#set working dir to the dir of the script
cd "$(dirname "$0")"

filename=$(basename "$1")
extension="${filename##*.}"
name="${filename%.*}"
dir=$(dirname "$1")

if [ "$extension" == "mb" ]; then
  ./mossvm "$dir/$filename"
else
  java -jar moss.jar $1 && ./mossvm "$dir/$name.mb"
fi
